import type { QuestionConfig } from "@/types/survey";

export const OTHER_OPTION = "기타";

export const CUSTOMER_QUESTIONS: QuestionConfig[] = [
  {
    id: "b1",
    title: "B1. 대출을 받아본 경험이 있나요?",
    type: "single",
    options: ["없음", "있음"],
    section: "customer",
  },
  {
    id: "b2",
    title: "B2. 받아본 대출 종류",
    description: "복수 선택 가능",
    type: "multi",
    options: [
      "신용대출",
      "주택담보대출",
      "전세자금대출",
      "사업자대출",
      "자동차대출",
      "카드론",
      "현금서비스",
      "주식담보대출",
      "보험계약대출",
      "마이너스통장",
      "P2P대출",
      "저축은행 대출",
      "대부업 대출",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "customer",
  },
  {
    id: "b3",
    title: "B3. 대출 규모",
    type: "single",
    options: [
      "1천만원 미만",
      "1천만~5천만원",
      "5천만~1억원",
      "1억~3억원",
      "3억~5억원",
      "5억원 이상",
    ],
    section: "customer",
  },
  {
    id: "b4",
    title: "B4. 최근 3년 이내 대출 경험",
    type: "single",
    options: ["있음", "없음"],
    section: "customer",
  },
  {
    id: "b5",
    title: "B5. 대출 이해도",
    type: "single",
    options: ["매우 낮음", "낮음", "보통", "높음", "매우 높음"],
    section: "customer",
  },
  {
    id: "b6",
    title: "B6. 대출 시 가장 중요하게 보는 요소 (중복선택)",
    type: "multi",
    options: [
      "금리",
      "한도",
      "승인 가능성",
      "상환 기간",
      "심사 속도",
      "중도상환수수료",
      "금융사 신뢰도",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "customer",
  },
  {
    id: "b7",
    title: "B7. 대출을 알아보는 방법 (중복선택)",
    type: "multi",
    options: [
      "은행 방문",
      "인터넷 검색",
      "대출 비교 플랫폼",
      "금융사 앱",
      "지인 소개",
      "대출 상담사",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "customer",
  },
  {
    id: "b8",
    title: "B8. 원하는 만큼 대출이 나오지 않아 다른 방법을 찾아본 경험",
    type: "single",
    options: [
      "있음",
      "없음",
      "기타(어떤 방법으로 했는지? [예 : 대출 전화, 부동산 소개등])",
    ],
    allowOther: true,
    otherLabel: "기타(어떤 방법으로 했는지? [예 : 대출 전화, 부동산 소개등])",
    section: "customer",
  },
  {
    id: "b9",
    title: "B9. 현재 대출 보유 여부",
    type: "single",
    options: ["있음", "없음"],
    section: "customer",
  },
];

export const FEEDBACK_QUESTIONS: QuestionConfig[] = [
  {
    id: "q1",
    title: "Q1. 사용 중 가장 불편했던 부분",
    description: "복수 선택",
    type: "multi",
    options: [
      "입력 항목이 많았다",
      "입력 항목이 이해되지 않았다",
      "결과가 늦게 나왔다",
      "화면 이동이 어색했다",
      "특별히 불편한 점은 없었다",
      "기타(직접입력)",
    ],
    allowOther: true,
    otherLabel: "기타(직접입력)",
    section: "feedback",
  },
  {
    id: "q2",
    title: "Q2. 상담 신청을 망설이게 만드는 가장 큰 이유",
    type: "single",
    options: [
      "업체를 신뢰하기 어렵다",
      "결과를 신뢰하기 어렵다",
      "개인정보 입력이 부담된다",
      "상담 자체가 부담된다",
      "더 많은 정보를 보고 싶다",
      "실제로 자금이 필요하지 않다",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q3",
    title: "Q3. 결과 화면에서 추가로 보고 싶었던 정보",
    description: "복수 선택",
    type: "multi",
    options: [
      "각 대출 업체 정보",
      "업체 리뷰",
      "업체 상담 사례",
      "예상 승인 가능성",
      "금리 산출 근거",
      "한도 산출 근거",
      "실제 승인 사례",
      "상담 진행 절차",
      "담당 상담사 정보",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q4",
    title: "Q4. 결과를 보고 가장 먼저 의심했던 부분",
    type: "single",
    options: [
      "한도가 너무 높게 나왔다",
      "금리가 너무 낮게 나왔다",
      "계산 근거를 모르겠다",
      "업체 정보가 부족하다",
      "실제 가능한 결과인지 모르겠다",
      "의심되는 부분은 없었다",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q5",
    title: "Q5. 서비스를 더 신뢰하게 만들기 위해 필요한 것",
    description: "최대 2개 선택",
    type: "multi",
    maxSelections: 2,
    options: [
      "실제 승인 사례",
      "실제 이용자 후기",
      "업체 정보 공개",
      "상담사 정보 공개",
      "사업자 정보 공개",
      "제휴 금융사 정보",
      "언론 기사 및 인증",
      "AI 분석 근거 공개",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q6",
    title: "Q6. 결과 확인 후 가장 먼저 보고 싶었던 것",
    type: "single",
    options: [
      "업체 상세 정보",
      "예상 한도 상세 보기",
      "예상 금리 상세 보기",
      "상담 신청",
      "승인 가능성 보기",
      "실제 사례 보기",
      "특별히 없었다",
    ],
    section: "feedback",
  },
  {
    id: "q7",
    title: "Q7. 현재 앱에서 가장 부족한 것",
    type: "single",
    options: [
      "신뢰성",
      "정보량",
      "디자인",
      "사용 편의성",
      "결과의 구체성",
      "업체 비교 기능",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q8",
    title: "Q8. 하나의 기능만 추가할 수 있다면",
    type: "single",
    options: [
      "업체 상세 정보",
      "실제 승인 사례",
      "승인 가능성 %",
      "금리 계산 근거",
      "한도 계산 근거",
      "후기 및 리뷰",
      "상담사 정보",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q9",
    title: "Q9. 실제 자금이 필요한 상황이라면 상담 신청 여부",
    type: "single",
    options: [
      "바로 신청한다",
      "추가 정보 확인 후 신청한다",
      "고민해본다",
      "신청하지 않는다",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
  {
    id: "q10",
    title: "Q10. 추가 정보 확인 후 신청한다면 필요한 정보",
    type: "multi",
    options: [
      "업체 정보",
      "실제 승인 사례",
      "승인 가능성",
      "후기",
      "상담사 정보",
      OTHER_OPTION,
    ],
    allowOther: true,
    section: "feedback",
  },
];

export const Q9_FOLLOW_UP_ANSWER = "추가 정보 확인 후 신청한다";
