import type { FinanceProvider } from '../types/providerComparison'

export const FINANCE_PROVIDERS: FinanceProvider[] = [
  {
    id: 'a',
    badge: 'A',
    name: 'A 대부중개',
    limit: '5.5억원',
    rate: '7.8%',
    tags: ['한도 높음', '금리 낮음'],
    repaymentPeriod: '최대 30년',
    prepaymentFee: '최대 1.2%',
    loanMethod: '원리금균등',
    feature: '한도 우대 가능',
    badgeColor: '#fff4d1',
  },
  {
    id: 'b',
    badge: 'B',
    name: 'B 캐피탈',
    limit: '4.8억원',
    rate: '8.8%',
    tags: ['금리 경쟁력', '심사 빠름'],
    repaymentPeriod: '최대 25년',
    prepaymentFee: '최대 1.5%',
    loanMethod: '원금균등',
    feature: '빠른 승인 프로세스',
    badgeColor: '#e8f4ff',
  },
  {
    id: 'c',
    badge: 'C',
    name: 'C 투자금융',
    limit: '6.0억원',
    rate: '9.5%',
    tags: ['사업자 특화', '유연한 조건'],
    repaymentPeriod: '최대 20년',
    prepaymentFee: '최대 2.0%',
    loanMethod: '원리금균등',
    feature: '사업자금 맞춤 설계',
    badgeColor: '#f3e8ff',
  },
  {
    id: 'd',
    badge: 'D',
    name: 'D 저축은행',
    limit: '4.2억원',
    rate: '8.2%',
    tags: ['안정적 금리', '신용 우대'],
    repaymentPeriod: '최대 30년',
    prepaymentFee: '최대 1.0%',
    loanMethod: '원리금균등',
    feature: '장기 상환 안정성',
    badgeColor: '#e8f8ef',
  },
  {
    id: 'e',
    badge: 'E',
    name: 'E 신용협동조합',
    limit: '3.6억원',
    rate: '7.6%',
    tags: ['지역 우대', '안정 조건'],
    repaymentPeriod: '최대 25년',
    prepaymentFee: '최대 0.8%',
    loanMethod: '원리금균등',
    feature: '지역 거주자 우대',
    badgeColor: '#fff0e8',
  },
  {
    id: 'f',
    badge: 'F',
    name: 'F 상호저축은행',
    limit: '4.5억원',
    rate: '8.5%',
    tags: ['중도금 연계', '담보 우대'],
    repaymentPeriod: '최대 30년',
    prepaymentFee: '최대 1.3%',
    loanMethod: '원리금균등',
    feature: '담보 가치 반영 우대',
    badgeColor: '#eef2ff',
  },
  {
    id: 'g',
    badge: 'G',
    name: 'G P2P금융',
    limit: '3.2억원',
    rate: '9.9%',
    tags: ['빠른 심사', '비대면'],
    repaymentPeriod: '최대 15년',
    prepaymentFee: '최대 2.5%',
    loanMethod: '원금균등',
    feature: '비대면 간편 신청',
    badgeColor: '#fce8f3',
  },
  {
    id: 'h',
    badge: 'H',
    name: 'H 온투업체',
    limit: '3.8억원',
    rate: '9.2%',
    tags: ['온라인 특화', '유연 심사'],
    repaymentPeriod: '최대 20년',
    prepaymentFee: '최대 2.0%',
    loanMethod: '원리금균등',
    feature: '온라인 전용 한도',
    badgeColor: '#e8faf5',
  },
  {
    id: 'i',
    badge: 'I',
    name: 'I 리스금융',
    limit: '5.0억원',
    rate: '8.9%',
    tags: ['리스 전환', '세제 혜택'],
    repaymentPeriod: '최대 25년',
    prepaymentFee: '최대 1.8%',
    loanMethod: '원리금균등',
    feature: '리스형 상환 선택',
    badgeColor: '#fff8e1',
  },
  {
    id: 'j',
    badge: 'J',
    name: 'J 보험사 할부',
    limit: '3.0억원',
    rate: '7.9%',
    tags: ['보험 연계', '금리 안정'],
    repaymentPeriod: '최대 20년',
    prepaymentFee: '최대 1.0%',
    loanMethod: '원리금균등',
    feature: '보험 가입 연계 우대',
    badgeColor: '#e3f2fd',
  },
  {
    id: 'k',
    badge: 'K',
    name: 'K 핀테크대출',
    limit: '4.0억원',
    rate: '8.6%',
    tags: ['AI 심사', '빠른 한도'],
    repaymentPeriod: '최대 25년',
    prepaymentFee: '최대 1.6%',
    loanMethod: '원리금균등',
    feature: 'AI 기반 한도 산정',
    badgeColor: '#f1f8e9',
  },
  {
    id: 'l',
    badge: 'L',
    name: 'L 지역농협',
    limit: '3.4억원',
    rate: '7.4%',
    tags: ['지역 특화', '금리 우대'],
    repaymentPeriod: '최대 30년',
    prepaymentFee: '최대 0.9%',
    loanMethod: '원리금균등',
    feature: '지역 거주·직장 우대',
    badgeColor: '#fff3e0',
  },
]
